### ISSUE TITLE
Need to force polling after hub restart

### ISSUE THREAD

**Issue by ryanmellish** [HubitatCommunity/HoneywellThermo-TCC#16]
After a hub restart, I noticed my 10 minute polling never began; symptom being a stale current temperature reported on my dashboard vs. the actual thermostat temperature. It appears that this may happen if the HE starts up after the poll next run time. I've solutioned by adding an initialize capability. I'd be happy to pull request if this is a feature that would be useful to others.

**Comment by bearmerino** [comment]
I have this same issue. Could you please share with me what you did?

**Comment by ryanmellish** [comment]
Yep, add the following:
my line 75: `capability "Initialize"`

my lines 701-704:
```
def initialize() {
    logInfo "Initialize Poll"
    poll()
}
```

**Comment by csteele-PD** [comment]
v1.3.13 to include this method.

**Comment by ryanmellish** [comment]
> v1.3.13 to include this method.

Thanks @csteele-PD. Only other thing I’m doing differently in HE is the `tccSite()` excluding ‘www’. This came up on the HE forum not too long ago. Does the driver still need this?

**Comment by csteele-PD** [comment]
I feel that field is 'user settable'. I've tested using the up-to-the-moment version of the driver and it's worked for me. In other words, it's not a universal requirement.
