### ISSUE TITLE
Problem with operatingState

### ISSUE THREAD

**Issue by MrJTT** [HubitatCommunity/HoneywellThermo-TCC#4]
First thanks for producing this driver.  I'm not an experience coder, but I'm very curious and I happened to stumble upon a fix for the problem I was having.  I thought I'd pass it on to you, in case you're interested.

With my thermostat(RTH6580WF), the driver was incorrectly reporting the operatingState.  When my thermostat was in heating the operatingState reported cooling.

In your current driver code, line 540 reads "if (mode == "heat")", to set the operatingState, but in the previous version your code read "if(equipmentStatus ==1)", to set the operatingState.  

I changed line 540 in my hubitat to "if(equipmentStatus ==1)" and it now reports the operatingState correctly.

Thanks again!

**Comment by csteele-PD** [comment]
Thanks, it will be corrected in the version I'm working on today.. I merged a Pull Request today and THEN saw this... so it will be in the next push I make.
