### ISSUE TITLE
thermostatMode bug?

### ISSUE THREAD

**Issue by jvmahon** [HubitatCommunity/HoneywellThermo-TCC#6]
In Version 1.3.3, the "thermostatMode" state seems to initialize with a copy of the Temperature value rather than one of the current target operating state of the thermostat selected by the user (i.e., one of ENUM ["heat", "cool", "emergency heat", "auto", "off"]). See image below. After selecting a state using the SetThermostatMode control in the Hubitat interface, it then displays a correct state. This looks like a bug in the initialization.

Initial state:
![image](https://user-images.githubusercontent.com/15061942/93018058-34099280-f59b-11ea-813d-f3844cbb2237.png)

After user selection of a state, this seems to fix:
![image](https://user-images.githubusercontent.com/15061942/93018213-0f61ea80-f59c-11ea-9289-e9ae6bd7c110.png)

**Comment by jvmahon** [comment]
Also, is it possible for you add in the "supportedThermostatsModes" attribute to distinguish thermostats that are used for heating-only, cooling-only, and auto?  I'm asking because I'm working on a Hubitat plugin for homebridge and its helpful to have the supportedThermostatsMode information to know what the Thermostat is doing.

**Comment by jvmahon** [comment]
I was able to find the bug (I think!) and submitted a pull request to correct this.

**Comment by KJ61** [comment]
Hi, seeing the exact same thing.

**Comment by jvmahon** [comment]
FYI - An updated version of the code was posted which fixes this issue, so I'm closing my original comment.
I understand the driver author is considering further updates, so keep a watch on this site over the next few weeks.
